name: Terraform Azure CI/CD - Multi-Environment

on:
  push:
    branches:
      - feature/module
      - qa  # Listen for pushes to both feature/module (for dev) and qa branches
      
# ADDED: This permission is required for the azure/login action to function correctly,
# even when using Service Principal secrets, as it handles token exchange internally.
permissions:
  id-token: write # Required for OIDC and token-based authentication
  contents: read # Default required for checking out code

# Define reusable secrets and parameters
env:
  # General Terraform settings
  TF_PLAN_FILE: 'tfplan' 
  
  # Azure Service Principal Credentials (Used by the provider to authenticate)
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # Azure Backend Storage Configuration (These must exist beforehand)
  BACKEND_RG_NAME: adf_project
  BACKEND_STORAGE_ACCOUNT: practeststorage
  BACKEND_CONTAINER_NAME: tfstate0310

jobs:

  # ====================================================================
  # JOB 1: PLAN - DEVELOPMENT (Triggered by 'feature/module' branch)
  # ====================================================================
  dev_plan:
    name: 'Dev - Plan'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/module'
    
    # Define environment-specific variables for this job
    env:
      ENV_NAME: dev
      # TF_ENV_DIR points to the root directory for this environment's code
      TF_ENV_DIR: environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # # Ensure Azure Login runs first to set credentials
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

       # ADDED: Debug step to list files in the working directory and its parent.
      - name: Debug File Paths
        run: |
          echo "Listing files in current working directory (${{ env.TF_ENV_DIR }}):"
          ls -al
          echo "Listing files in parent directory (expected location of .tfvars):"
          ls -al ..
        working-directory: ${{ env.TF_ENV_DIR }}

      # DEBUG STEP: Verify paths before init
      - name: Debug Environment Variables
        run: |
          echo "TF_ENV_DIR is: ${{ env.TF_ENV_DIR }}"
          echo "ENV_NAME is: ${{ env.ENV_NAME }}"
          echo "Expected var-file path: ${{ env.ENV_NAME }}.tfvars" # Reverted to correct path
        working-directory: ${{ env.TF_ENV_DIR }}

      # Initialize backend with environment-specific state key
      - name: Terraform Init & Validate
        id: init
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.BACKEND_RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENV_NAME }}/${{ github.sha }}.tfstate"
          
          terraform validate
          terraform fmt -check -recursive
        working-directory: ${{ env.TF_ENV_DIR }}

      # FIX APPLIED: Path reverted to look for the file in the current working directory
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=${{ env.TF_PLAN_FILE }} -var-file="${{ env.ENV_NAME }}.tfvars" -detailed-exitcode
        working-directory: ${{ env.TF_ENV_DIR }}

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-plan-artifact
          path: ${{ env.TF_ENV_DIR }}/${{ env.TF_PLAN_FILE }}

  # ====================================================================
  # JOB 2: APPLY - DEVELOPMENT (Auto-apply on 'feature/module' branch)
  # ====================================================================
  dev_apply:
    name: 'Dev - Apply'
    runs-on: ubuntu-latest
    needs: [dev_plan]
    if: success() && github.ref == 'refs/heads/feature/module' 
    
    environment: development 
    
    env:
      ENV_NAME: dev
      TF_ENV_DIR: environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-plan-artifact
          path: ${{ env.TF_ENV_DIR }}

      - name: Terraform Init (for apply context)
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.BACKEND_RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENV_NAME }}/${{ github.sha }}.tfstate"
        working-directory: ${{ env.TF_ENV_DIR }}
        
      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ env.TF_PLAN_FILE }}
        working-directory: ${{ env.TF_ENV_DIR }}


  # ====================================================================
  # JOB 3: PLAN - qa (Triggered by 'qa' branch)
  # ====================================================================
  qa_plan:
    name: 'qa - Plan'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/qa'
    
    env:
      ENV_NAME: qa
      TF_ENV_DIR: environments/qa 
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # DEBUG STEP: Verify paths before init
      - name: Debug Environment Variables
        run: |
          echo "TF_ENV_DIR is: ${{ env.TF_ENV_DIR }}"
          echo "ENV_NAME is: ${{ env.ENV_NAME }}"
          echo "Expected var-file path: ${{ env.ENV_NAME }}.tfvars" # Reverted to correct path
        working-directory: ${{ env.TF_ENV_DIR }}
        
      # Initialize backend with environment-specific state key
      - name: Terraform Init & Validate
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.BACKEND_RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENV_NAME }}/${{ github.sha }}.tfstate"
          
          terraform validate
          terraform fmt -check -recursive
        working-directory: ${{ env.TF_ENV_DIR }}

      # FIX APPLIED: Path reverted to look for the file in the current working directory
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=${{ env.TF_PLAN_FILE }} -var-file="${{ env.ENV_NAME }}.tfvars" -detailed-exitcode
        working-directory: ${{ env.TF_ENV_DIR }}

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qa-plan-artifact
          path: ${{ env.TF_ENV_DIR }}/${{ env.TF_PLAN_FILE }}


  # ====================================================================
  # JOB 4: APPLY - qa (Requires Manual Approval)
  # ====================================================================
  qa_apply:
    name: 'qa - Apply'
    runs-on: ubuntu-latest
    needs: [qa_plan]
    if: success() && github.ref == 'refs/heads/qa' 

    environment: 
      name: qa
      url: https://portal.azure.com/ 

    env:
      ENV_NAME: qa
      TF_ENV_DIR: environments/qa
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: qa-plan-artifact
          path: ${{ env.TF_ENV_DIR }}

      - name: Terraform Init (for apply context)
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.BACKEND_RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENV_NAME }}/${{ github.sha }}.tfstate"
        working-directory: ${{ env.TF_ENV_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ env.TF_PLAN_FILE }} -var-file="${{ env.ENV_NAME }}.tfvars"
        working-directory: ${{ env.TF_ENV_DIR }}
